### ISSUE TITLE
pip requeriments

### ISSUE THREAD

**Issue by jdbravo** [malwaru/person_following_robot#2]
Hi,

I'm getting those errors trying to install the requerimients for your fork of ByteTrack:

ERROR: Could not find a version that satisfies the requirement model==0.6.0 (from versions: none)
ERROR: No matching distribution found for model==0.6.0
ERROR: Could not find a version that satisfies the requirement backbone==0.6.0 (from versions: none)
ERROR: No matching distribution found for backbone==0.6.0

And if I remove those depences, the pip install -r requeriments.txt fails with this error:

 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [322 lines of output]
      warning: pandas/_libs/algos_take_helper.pxi:89:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:145:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:349:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:405:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:609:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:665:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:869:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:925:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:1129:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:1185:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:1389:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:1445:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:1649:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:1705:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:1909:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:1965:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:2169:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:2225:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:2429:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:2485:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:2689:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:2745:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:2949:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:3005:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:3209:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:3265:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:3469:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:3525:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:3729:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:3785:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:3989:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:4045:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:4249:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:4305:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:4509:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:4565:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:4769:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos_take_helper.pxi:4825:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pandas/_libs/algos.pyx:115:42: Unknown type declaration 'bint' in annotation, ignoring
      performance hint: pandas/_libs/hashing.pyx:97:5: Exception check on 'u32to8_le' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashing.pyx:115:5: Exception check on '_sipround' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashing.pyx:159:21: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashing.pyx:170:17: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashing.pyx:176:17: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable_class_helper.pxi:21:5: Exception check on 'append_data_float64' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable_class_helper.pxi:30:5: Exception check on 'append_data_int64' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable_class_helper.pxi:43:5: Exception check on 'append_data_string' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable_class_helper.pxi:56:5: Exception check on 'append_data_uint64' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable_class_helper.pxi:542:39: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable_class_helper.pxi:655:39: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable_class_helper.pxi:847:38: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable_class_helper.pxi:957:38: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable_class_helper.pxi:1149:37: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable_class_helper.pxi:1262:37: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/hashtable.pyx:166:33: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/parsers.pyx:1675:5: Exception check on '_to_fw_string_nogil' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      warning: pandas/_libs/parsers.pyx:1726:34: Casting a GIL-requiring function into a nogil function circumvents GIL validation
      performance hint: pandas/_libs/parsers.pyx:1670:27: Exception check will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      performance hint: pandas/_libs/parsers.pyx:1769:42: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: pandas/_libs/parsers.pyx:1790:38: Exception check will always require the GIL to be acquired. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  object cached_typ=None
      
              arr = self.arr
              chunk = self.dummy
              dummy_buf = chunk.data
              chunk.data = arr.data
                   ^
      ------------------------------------------------------------
      
      pandas/_libs/reduction.pyx:113:13: Assignment to a read-only property
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                                                     self.nresults,
                                                     len(self.dummy))
                          it = <flatiter>PyArray_IterNew(result)
      
                      PyArray_SETITEM(result, PyArray_ITER_DATA(it), res)
                      chunk.data = chunk.data + self.increment
                           ^
      ------------------------------------------------------------
      
      pandas/_libs/reduction.pyx:167:21: Assignment to a read-only property
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  if hasattr(e, 'args'):
                      e.args = e.args + (i,)
                  raise
              finally:
                  # so we don't free the wrong memory
                  chunk.data = dummy_buf
                       ^
      ------------------------------------------------------------
      
      pandas/_libs/reduction.pyx:175:17: Assignment to a read-only property
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  if hasattr(e, 'args'):
                      e.args = e.args + (i,)
                  raise
              finally:
                  # so we don't free the wrong memory
                  chunk.data = dummy_buf
                       ^
      ------------------------------------------------------------
      
      pandas/_libs/reduction.pyx:175:17: Assignment to a read-only property
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
              self.orig_data = self.buf.data
              self.orig_len = self.buf.shape[0]
              self.orig_stride = self.buf.strides[0]
      
              self.buf.data = self.values.data
                      ^
      ------------------------------------------------------------
      
      pandas/_libs/reduction.pyx:480:16: Assignment to a read-only property
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
              self.buf.data = self.values.data
              self.buf.strides[0] = self.stride
      
          cpdef advance(self, Py_ssize_t k):
              self.buf.data = <char*>self.buf.data + self.stride * k
                      ^
      ------------------------------------------------------------
      
      pandas/_libs/reduction.pyx:484:16: Assignment to a read-only property
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
          cdef move(self, int start, int end):
              """
              For slicing
              """
              self.buf.data = self.values.data + self.stride * start
                      ^
      ------------------------------------------------------------
      
      pandas/_libs/reduction.pyx:490:16: Assignment to a read-only property
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.buf.shape[0] = length
      
          cpdef reset(self):
      
              self.buf.shape[0] = self.orig_len
              self.buf.data = self.orig_data
                      ^
      ------------------------------------------------------------
      
      pandas/_libs/reduction.pyx:499:16: Assignment to a read-only property
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              # move blocks
              for i in range(self.nblocks):
                  arr = self.blocks[i]
      
                  # axis=1 is the frame's axis=0
                  arr.data = self.base_ptrs[i] + arr.strides[1] * start
                     ^
      ------------------------------------------------------------
      
      pandas/_libs/reduction.pyx:609:15: Assignment to a read-only property
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              # reset blocks
              for i in range(self.nblocks):
                  arr = self.blocks[i]
      
                  # axis=1 is the frame's axis=0
                  arr.data = self.base_ptrs[i]
                     ^
      ------------------------------------------------------------
      
      pandas/_libs/reduction.pyx:627:15: Assignment to a read-only property
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-fittch2n/pandas_870b687c969946629d9eda295cb2e837/setup.py", line 815, in <module>
          ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
        File "/tmp/pip-install-fittch2n/pandas_870b687c969946629d9eda295cb2e837/setup.py", line 544, in maybe_cythonize
          return cythonize(extensions, *args, **kwargs)
        File "/home/jbravo/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/home/jbravo/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pandas/_libs/reduction.pyx
      Compiling pandas/_libs/algos.pyx because it changed.
      Compiling pandas/_libs/groupby.pyx because it changed.
      Compiling pandas/_libs/hashing.pyx because it changed.
      Compiling pandas/_libs/hashtable.pyx because it changed.
      Compiling pandas/_libs/index.pyx because it changed.
      Compiling pandas/_libs/indexing.pyx because it changed.
      Compiling pandas/_libs/internals.pyx because it changed.
      Compiling pandas/_libs/interval.pyx because it changed.
      Compiling pandas/_libs/join.pyx because it changed.
      Compiling pandas/_libs/lib.pyx because it changed.
      Compiling pandas/_libs/missing.pyx because it changed.
      Compiling pandas/_libs/parsers.pyx because it changed.
      Compiling pandas/_libs/reduction.pyx because it changed.
      Compiling pandas/_libs/ops.pyx because it changed.
      Compiling pandas/_libs/properties.pyx because it changed.
      Compiling pandas/_libs/reshape.pyx because it changed.
      Compiling pandas/_libs/skiplist.pyx because it changed.
      Compiling pandas/_libs/sparse.pyx because it changed.
      Compiling pandas/_libs/tslib.pyx because it changed.
      Compiling pandas/_libs/tslibs/c_timestamp.pyx because it changed.
      Compiling pandas/_libs/tslibs/ccalendar.pyx because it changed.
      Compiling pandas/_libs/tslibs/conversion.pyx because it changed.
      Compiling pandas/_libs/tslibs/fields.pyx because it changed.
      Compiling pandas/_libs/tslibs/frequencies.pyx because it changed.
      Compiling pandas/_libs/tslibs/nattype.pyx because it changed.
      Compiling pandas/_libs/tslibs/np_datetime.pyx because it changed.
      Compiling pandas/_libs/tslibs/offsets.pyx because it changed.
      Compiling pandas/_libs/tslibs/parsing.pyx because it changed.
      Compiling pandas/_libs/tslibs/period.pyx because it changed.
      Compiling pandas/_libs/tslibs/resolution.pyx because it changed.
      Compiling pandas/_libs/tslibs/strptime.pyx because it changed.
      Compiling pandas/_libs/tslibs/timedeltas.pyx because it changed.
      Compiling pandas/_libs/tslibs/timestamps.pyx because it changed.
      Compiling pandas/_libs/tslibs/timezones.pyx because it changed.
      Compiling pandas/_libs/tslibs/tzconversion.pyx because it changed.
      Compiling pandas/_libs/testing.pyx because it changed.
      Compiling pandas/_libs/window.pyx because it changed.
      Compiling pandas/_libs/writers.pyx because it changed.
      Compiling pandas/io/sas/sas.pyx because it changed.
      Compiling pandas/io/msgpack/_packer.pyx because it changed.
      Compiling pandas/io/msgpack/_unpacker.pyx because it changed.
      [ 1/41] Cythonizing pandas/_libs/algos.pyx
      [ 2/41] Cythonizing pandas/_libs/groupby.pyx
      [ 3/41] Cythonizing pandas/_libs/hashing.pyx
      [ 4/41] Cythonizing pandas/_libs/hashtable.pyx
      [ 5/41] Cythonizing pandas/_libs/index.pyx
      [ 6/41] Cythonizing pandas/_libs/indexing.pyx
      [ 7/41] Cythonizing pandas/_libs/internals.pyx
      [ 8/41] Cythonizing pandas/_libs/interval.pyx
      [ 9/41] Cythonizing pandas/_libs/join.pyx
      [10/41] Cythonizing pandas/_libs/lib.pyx
      [11/41] Cythonizing pandas/_libs/missing.pyx
      [12/41] Cythonizing pandas/_libs/ops.pyx
      [13/41] Cythonizing pandas/_libs/parsers.pyx
      [14/41] Cythonizing pandas/_libs/properties.pyx
      [15/41] Cythonizing pandas/_libs/reduction.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

python3 --version
Python 3.10.12

On ubuntu 22.04

Any idea ?

thanks,

**Comment by malwaru** [comment]
I didnt get the time to recreate the issue . I have two alternatives that might help you as a quick fix.

1. Try removing the model and backbone packages from the requirements file. Install the rest of the the packages then when you are trying to run the code if the program gives an error saying its missing some packages then install them and see.

2.  Use the original bytetrack not my fork  then just add the following function in the  "**ByteTrack /yolox/utils/demo_utils.py"** file 
```
def get_path():

    return pathlib.Path(__file__).parents[2].resolve()
```
